Renamed all instance of Person to Patient
AY2324S1-CS2103T-T14-2/tp pull request #68
Opened 2023-10-05 16:05 UTC by AaronJT1

## What is changed
1.  For the source code, renamed all instances of 'Person' to 'Patient' in  all components (UI, Model, Storage,...) .
2. For the testing code, renamed all instances of 'Person' to 'Patient'.

2023-10-05 16:27 UTC, longnguyentan commented on src/main/java/seedu/address/logic/commands/EditCommand.java
> +import seedu.address.model.patient.*;
Using the '.*' form of import should be avoided

2023-10-05 16:29 UTC, longnguyentan commented on src/main/java/seedu/address/model/util/SampleDataUtil.java
> +import seedu.address.model.patient.*;
Using the '.*' form of import should be avoided

2023-10-05 16:29 UTC, longnguyentan commented on src/main/java/seedu/address/storage/JsonAdaptedPatient.java
> +import seedu.address.model.patient.*;
Using the '.*' form of import should be avoided

2023-10-05 16:30 UTC, longnguyentan requested changes
@AaronJT1 @wujy28 @thienmy0 @RiyaMehta2211 Guys, remember to run `Checkstyle` before committing the code
@longnguyentan

2023-10-06 01:47 UTC, AaronJT1 commented
Hi, thanks for suggestions, have done the necessary checkstyles checks!

2023-10-07 05:35 UTC, merged